// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvrOG3pd9xcE2ylHzm1DX7GW06R0JLjIs',
    appId: '1:761617478948:web:dd2b0c3497fba2acda2fb1',
    messagingSenderId: '761617478948',
    projectId: 'gamevault-e40b0',
    authDomain: 'gamevault-e40b0.firebaseapp.com',
    storageBucket: 'gamevault-e40b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYVwCytvfHGDA0S6wot6hQt-SToD_IXeQ',
    appId: '1:761617478948:android:3e53774d9e07e226da2fb1',
    messagingSenderId: '761617478948',
    projectId: 'gamevault-e40b0',
    storageBucket: 'gamevault-e40b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5eJmL1d7AU1uZ7vN3wDO2UdywpO5GvtY',
    appId: '1:761617478948:ios:35a6ba844368a76eda2fb1',
    messagingSenderId: '761617478948',
    projectId: 'gamevault-e40b0',
    storageBucket: 'gamevault-e40b0.firebasestorage.app',
    iosBundleId: 'com.example.gamevault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5eJmL1d7AU1uZ7vN3wDO2UdywpO5GvtY',
    appId: '1:761617478948:ios:35a6ba844368a76eda2fb1',
    messagingSenderId: '761617478948',
    projectId: 'gamevault-e40b0',
    storageBucket: 'gamevault-e40b0.firebasestorage.app',
    iosBundleId: 'com.example.gamevault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvrOG3pd9xcE2ylHzm1DX7GW06R0JLjIs',
    appId: '1:761617478948:web:13049e90ff91d53dda2fb1',
    messagingSenderId: '761617478948',
    projectId: 'gamevault-e40b0',
    authDomain: 'gamevault-e40b0.firebaseapp.com',
    storageBucket: 'gamevault-e40b0.firebasestorage.app',
  );
}
